version: "3.8"

services:
  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: auth-detector-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - auth-detector-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-detector-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    depends_on:
      - redis
    networks:
      - auth-detector-network
    volumes:
      - ./logs:/app/logs

networks:
  auth-detector-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
